language: java
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - openjdk-ea

matrix:
  allow_failures:
    - jdk: openjdk-ea

script: mvn clean install -U

after_success:
  - mvn clean test jacoco:report coveralls:report