name: github-push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 8, 11, 15 ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
    - run: mvn -B install --no-transfer-progress --file pom.xml

    - name: Setup Java for publishing to GitHub Packages (only with Java 8)
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Publish SNAPSHOT version to GitHub Packages
      run: mvn -B --no-transfer-progress deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}